Frontend:
  Translation:
    impl: RandomTranslation
    max_addr: 2147483648
  clock_ratio: 8
  impl: SimpleO3
  num_expected_insts: 10000000
  traces:
  - ./cputraces/429.mcf
MemorySystem:
  AddrMapper:
    impl: MOP4CLXOR
  Controller:
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy

    Scheduler:
      impl: FRFCFS_blacklisting
    impl: Blacklisting
    plugins:
    - ControllerPlugin:
        activation_threshold: 63
        impl: GrapheneDDR5
        num_table_entries: 21760
        queue_type: read
        insecure_read_queue: false
        reset_period_ns: 32000000
        tRH: 125
  DRAM:
    RFM: null
    current: null
    drampower_enable: true
    impl: DDR5
    org:
      channel: 2
      preset: DDR5_8Gb_x16
      rank: 2
    timing:
      preset: DDR5_3200AN
    voltage: null
  clock_ratio: 3
  impl: GenericDRAM
